---
:ems:
  :ems_openshift:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:hawkular_tenant_labels:
  :_hawkular_admin: Hawkular Admin
:http_proxy:
  :openshift:
    :host:
    :password:
    :port:
    :user:
:ems_refresh:
  :openshift:
    :refresh_interval: 15.minutes
    :streaming_refresh: true
    :chunk_size: 1_000
    :inventory_collections:
      :saver_strategy: batch
    :get_container_images: true
    :store_unused_images: true
:workers:
  :ems_metrics_collector_worker_openshift:
    :inherits_from: ems_metrics_collector_worker
  :ems_refresh_worker_openshift:
    :inherits_from: ems_refresh_worker
  :event_catcher_openshift:
    :inherits_from: event_catcher
    :poll: 1.seconds
  :event_catcher_prometheus:
    :inherits_from: event_catcher
    :poll: 20.seconds
